# Generated by Django 5.2.6 on 2025-09-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('roles', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
