# Generated by Django 5.2.6 on 2025-09-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='roles',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='09:00'),
        ),
    ]
