# Generated by Django 5.2.6 on 2025-09-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_event_roles_event_tags_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
