# Generated by Django 5.2.6 on 2025-10-01 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_event_date'),
        ('events', '0008_delete_allevents_alter_registration_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='HomePageEvent',
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_registrations', to='events.event'),
        ),
    ]
