# Generated by Django 5.2.6 on 2025-09-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_roles_event_tags_event_time_alter_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('languages_known', models.CharField(max_length=100)),
                ('current_status', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('working', 'Working'), ('other', 'Other')], max_length=20)),
                ('preferred_days', models.CharField(max_length=100)),
                ('specific_dates', models.CharField(blank=True, max_length=100)),
                ('preferred_time_slots', models.CharField(max_length=100)),
                ('has_experience', models.BooleanField(default=False)),
                ('experience_details', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default='09:00'),
        ),
    ]
