# Generated by Django 5.2.6 on 2025-09-29 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_volunteer_alter_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='languages_known',
            new_name='languages',
        ),
    ]
