# Generated by Django 5.2.6 on 2025-10-01 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllEvents',
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='events.event'),
        ),
    ]
