# Generated by Django 5.2.6 on 2025-10-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_registration_event'),
        ('events', '0008_delete_allevents_alter_registration_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
