# Generated by Django 5.2.6 on 2025-10-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_registration_event_delete_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='experience_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='specific_dates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
